config/routes.rb
AdminBackend::Engine.routes.draw do
	root :to => 'dashboard#index'
	resources :accounts do
		resources :users do
			member do
				get 'activate'
				get 'deactivate'
				get 'set_account_owner'
			end
		end
	end
	get 'users', :to => 'users#index'
	get 'reports', :to => 'reports#index'
end

app/controllers/admin_backend/accounts_controller.rb
require_dependency "admin_backend/application_controller"

module AdminBackend
  class AccountsController < ApplicationController
  	before_filter :authenticate_user!
  	before_filter :authenticate_super_user?

    def index
    	@accounts = Account.all
    end

    def show
    	@account = Account.find(params[:id])
    	@users = @account.users
    end

    # creating a user that is an account owner
    def new
      @account = Account.new
    end

    # creating a user that is an account owner
    def create
      @account = Account.new(account_params)
      if @account.save
        redirect_to @account 
      else
        render action: "new"
      end
    end

    private
    def account_params
      params.require(:account).permit(:title, 
        :account_type, :description, :address_line1, :addressline2, :suburb, :post_code, :state, 
        :country, :phone, :email, :website )  
    end
  end
end


# get all records that belongs to account 
# ActiveRecord::Base.subclasses.each do |sc| 
#    if sc.column_names.include?('account_id') 
#           sc.where(account_id: @account.id).count
#     end 
# end 

app/controllers/admin_backend/application_controller.rb
module AdminBackend
  class ApplicationController < ActionController::Base
	# Authenticate super user
	def authenticate_super_user?
		redirect_to main_app.root_path unless current_user.is_super_user?
	end  
	helper_method :authenticate_super_user?
  end
end

app/controllers/admin_backend/dashboard_controller.rb
require_dependency "admin_backend/application_controller"

module AdminBackend
  class DashboardController < ApplicationController
  	before_filter :authenticate_user!
  	before_filter :authenticate_super_user?
    def index
    	@accounts = Account.all
    	@users = User.all
    end
  end
end

app/controllers/admin_backend/reports_controller.rb
require_dependency "admin_backend/application_controller"

module AdminBackend
  class ReportsController < ApplicationController
  	before_filter :authenticate_user!
  	before_filter :authenticate_super_user?
    def index
    end
  end
end

app/controllers/admin_backend/users_controller.rb
require_dependency "admin_backend/application_controller"

module AdminBackend
  class UsersController < ApplicationController
  	before_filter :authenticate_user!
  	before_filter :authenticate_super_user?
  	def index
  		@users = User.all
  	end

  	def show
  		@user = User.find(params[:id])
  	end

    def new
      @account = Account.find(params[:account_id])
      @user = User.new
    end

    def create
      @account = Account.find(params[:account_id])
      @user = User.new(user_params)
      if @user.save
        redirect_to [@account, @user] 
      else  
        render action: "new"
      end
    end

    def activate
      @user = User.find(params[:id])
      @user.active = true
      @user.save

      redirect_to :back
    end

    def deactivate
      @user = User.find(params[:id])
      @user.active = false
      @user.save

      redirect_to :back
    end

    def set_account_owner
      @account = Account.find(params[:account_id])
      @user = User.find(params[:id])

      @user.account_owner = true
      @user.save

      @account.user_id = @user.id
      @account.save

      if @account.users.count > 1
        @account.users.where.not(id: @user.id).each do |user|
          if user.account_owner == true
            user.account_owner = false
            user.save
          end
        end
      end
      redirect_to :back
    end

    private
    def user_params
      if params[:action] == 'create'
        params[:user][:created_by]=current_user.id
        params[:user][:created_ip]=request.remote_ip
        params[:user][:account_id]=@account.id
      end
      params[:user][:updated_by]=current_user.id
      params[:user][:updated_ip]=request.remote_ip
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :account_id, :created_by, :created_ip, :updated_by, :updated_ip)  
    end
  end
end

app/helpers/admin_backend/accounts_helper.rb
module AdminBackend
  module AccountsHelper
  end
end

app/helpers/admin_backend/application_helper.rb
module AdminBackend
  module ApplicationHelper
  end
end

app/helpers/admin_backend/dashboard_helper.rb
module AdminBackend
  module DashboardHelper
  end
end

app/helpers/admin_backend/reports_helper.rb
module AdminBackend
  module ReportsHelper
  end
end

app/helpers/admin_backend/users_helper.rb
module AdminBackend
  module UsersHelper
  end
end

app/views/admin_backend/accounts/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Accounts
            <%= link_to 'Create account', new_account_path, class: "btn btn-default pull-right" %>
        </h1>
        <table class="table table-striped" id="dataTables-accounts">
            <thead>
        	<tr>
        		<th>ID</th><th>Title</th><th>Created at</th><th></th>
        	</tr>
            </thead>
            <tbody>
	        <% @accounts.each do |account| %>
	        	<tr>
	        		<td><%= account.id %></td>
	        		<td><%= account.title %></td>
	        		<td><%= account.created_at %></td>
	        		<td class="text-right"><%= link_to "View", account %></td>
	        	</tr>
	        <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/admin_backend/accounts/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">New Account</h1>
		<%= simple_form_for @account do |f| %>
			<%= f.input :title %>
			<%= f.input :account_type %>
			<%= f.input :description %>
			<div class="row">
				<div class="col-md-6">
				<%= f.input :address_line1, label: 'Address line 1' %>
				</div>
				<div class="col-md-6">
				<%= f.input :address_line2, label: 'Address line 2' %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-3">
				<%= f.input :suburb %>
				</div>
				<div class="col-md-3">
				<%= f.input :post_code, label: 'Postcode' %>
				</div>
				<div class="col-md-3">
				<%= f.input :state %>
				</div>
				<div class="col-md-3">
				<%= f.input :country, input_html: {class: "form-control"} %>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<%= f.input :phone %>
				</div>
				<div class="col-md-4">
					<%= f.input :email %>
				</div>
				<div class="col-md-4">
					<%= f.input :website %>
				</div>
			</div>
			<%= f.button :submit %>
		<% end %>
    </div>
</div>

app/views/admin_backend/accounts/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Accounts <small><%=@account.title%></small>
            <%= link_to 'Create user', new_account_user_path(@account), class: "btn btn-default pull-right" %>
        </h1>

        <h4>Users</h4>
        <div class="">
            <table class="table table-striped table-bordered-outer" id="dataTables-users">
                <thead>
                    <tr><th>Email</th><th>First name</th><th>Last name</th><th>Account owner</th><th>Created at</th><th></th></tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td><%= user.email%></td>
                            <td><%= user.first_name %></td>
                            <td><%= user.last_name %></td>
                            <td><%= user.account_owner %></td>
                            <td><%= user.created_at %></td>
                            <td class="text-right"><%= link_to "View", account_user_path(user.account_id, user) %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/admin_backend/dashboard/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
        <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-users fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%=@accounts.count%></div>
                                    <div>Accounts</div>
                                </div>
                            </div>
                        </div>
                        <a href="<%=accounts_path%>">
                            <div class="panel-footer">
                                <span class="pull-left">View</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-green">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-3">
                                    <i class="fa fa-user fa-5x"></i>
                                </div>
                                <div class="col-xs-9 text-right">
                                    <div class="huge"><%=@users.count%></div>
                                    <div>Users</div>
                                </div>
                            </div>
                        </div>
                        <a href="<%=users_path%>">
                            <div class="panel-footer">
                                <span class="pull-left">View</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
    </div>
</div>

app/views/admin_backend/reports/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Reports</h1>
		<table class="table table-striped">
            <tr><th>Record</th><th>Number of records</th></tr>
			<% ActiveRecord::Base.subclasses.each do |sc| %>
				<% unless sc.model_name == "ActiveRecord::SchemaMigration" %>
				    <tr>
				        <td><%= sc.model_name %></td><td><%= sc.count %></td>
				    </tr>
			    <% end %>
			<% end %>
		</table>
	</div>
</div>

app/views/admin_backend/users/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Users</h1>
        <table class="table table-striped" id="dataTables-users">
        	<thead>
        	<tr>
        		<th>ID</th><th>Email</th><th>Created</th><th>Last sign in</th><th></th>
        	</tr>
        	</thead>
        	<tbody>
	        <% @users.each do |user| %>
	        	<tr>
	        		<td><%= user.id %></td>
	        		<td><%= user.email %></td>
	        		<td><%= user.created_at %></td>
	        		<td><%= user.last_sign_in_at %></td>
	        		<td class="text-right"><%= link_to "View", account_user_path(user.account_id, user) %></td>
	        	</tr>
	        <% end %>
	        </tbody>
        </table>
    </div>
</div>

app/views/admin_backend/users/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">New User <small><%= @account.title %></small></h1>
			<%= simple_form_for [@account, @user] do |f| %>
				<%= f.input :email %>
				<%= f.input :first_name %>
				<%= f.input :last_name %>
				<%= f.input :password %>
				<%= f.input :password_confirmation %>
				<%= f.button :submit %>
			<% end %>
    </div>
</div>

app/views/admin_backend/users/show.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">User <small><%=@user.email%></small> <!-- Single button -->
			<div class="btn-group pull-right">
			  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
			    Action <span class="caret"></span>
			  </button>
			  <ul class="dropdown-menu" role="menu">
			    <li><%= link_to 'Activate', activate_account_user_path(@user.account_id, @user) if !@user.active %>
			    	<%= link_to 'Deactivate', deactivate_account_user_path(@user.account_id, @user) if @user.active %></li>
                <li><%= link_to 'Set account owner', set_account_owner_account_user_path(@user.account_id, @user) if @user.active %></li>
			  </ul>
			</div>
		</h1>

        <table class="table table-striped">
        	<tr><td>Email</td><td><%= @user.email %></td></tr>
        	<tr><td>First name</td><td><%= @user.first_name %></td></tr>
        	<tr><td>Last name</td><td><%= @user.last_name %></td></tr>
        	<tr><td>Account owner</td><td><%= @user.account_owner %></td></tr>
        	<tr><td>Account</td><td><%= link_to 'View account', account_path(@user.account_id) %></td></tr>
        	<tr><td>Active</td><td><%= @user.active %></td></tr>
        	<tr><td>Created at</td><td><%= @user.created_at %></td></tr>
        	<tr><td>Current sign in at</td><td><%= @user.current_sign_in_at %></td></tr>
        	<tr><td>Last sign in at</td><td><%= @user.last_sign_in_at %></td></tr>
        </table>
    </div>
</div>

app/views/layouts/admin_backend/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdminBackend</title>
  <%= stylesheet_link_tag    "application", media: "all", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", 'data-turbolinks-track' => true  %>
  <%= stylesheet_link_tag    "admin_backend/application", media: "all", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "admin_backend/application", 'data-turbolinks-track' => true  %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Admin Backend", root_path, class: "navbar-brand" %>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li><%= link_to "<i class='fa fa-fw fa-dashboard'></i> Dashboard".html_safe, root_path, class: (controller_name == "dashboard" ? "active" : "") %></li>
                    	<li><%= link_to "<i class='fa fa-fw fa-users'></i> Accounts".html_safe, accounts_path, class: (controller_name == "accounts" ? "active" : "") %></li>
                    	<li><%= link_to "<i class='fa fa-fw fa-user'></i> Users".html_safe, users_path, class: (controller_name == "users" ? "active" : "") %></li>
                    	<li><%= link_to "<i class='fa fa-fw fa-signal'></i> Reports".html_safe, reports_path, class: (controller_name == "reports" ? "active" : "") %></li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
            	<%= yield %>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->
</body>
</html>